version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: service1
    ports:
      - "8001:8001"   # Exposes 8001 to the host (for browser access)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  service2:
    build: ./service_2
    container_name: service2
    ports:
      - "8002:8002"   # Exposes 8002 to the host (for browser access)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
